#+STARTUP: showall
#+STARTUP: lognotestate
#+TAGS:
#+SEQ_TODO: TODO STARTED DONE DEFERRED CANCELLED | WAITING DELEGATED APPT
#+DRAWERS: HIDDEN STATE
#+TITLE: Notes and TODOs for R-channels paper
#+CATEGORY: todo

* <2016-01-17 Sun>


For "theory" section

    In the last decade, Stack Overflow has become the most popular \channel for answering software development related questions, nearly replacing previous methods of communication that accomplished the same objective~\cite{Vasilescu2014c}.
    Despite Stack Overflow's advantages over Q\&A mailing lists such as the R-help (i.e., gamification environment and rich visual user interface), there are still many users who prefer the latter.
    We will learn the way programmers use Stack Overflow and the R-help mailing list to gain and share knowledge.

* FOr that chapter

- importance of the community of practice
 - developers benefit from it

- CPs questions:
 - What channels to support?
 - 


- We will concentrate on knowledge creation and curation, hence we will look only at q&a in both media
- MLs are the old channel
- SO is the new kid in town
- Why hasn't one replaced the other?
  - do they support the community in different ways?
  - Why do developers choose one over the other?
  - Do they provide different benefits to the community?

* When I have internet:

- search for flashmob in slashdot

The R community is vibrant and keeps growing at a very fast rate. 

The R language continues to growth in popularity, and with it, the size of its community of practice. The recent TIOBE index for Programming Languages ranks it
number 19 among all languages.  According to a recent survey, R has become the highest paying skill in IT. The interest in R continues to grow. Few weeks ago
Microsoft announced support for R in Visual Studio\cite{r-microsot}.

Being an open source project, without commercial backing, the R community has played an important role in its diffusion. Those new to the R language have
numerous resources to learn the language and receive help: mailing lists, blogs, books, online- and offine--courses, questions-and-answers sites (such as
\so). In all, these resources provide a vast and rich corpus of knowledge. The R-community benefit from this corpus, but it also the one that drives its
creation and curation.  For example, in July of 2009, during the Open Source Convention (OSCON'09), the organizers of a birds-of-a-feather session invited users
to participate in a Flashmob to seed Stackoverflow with R related questions\cite{rflashmob09}. The premise of the session was that \so lacked R-related
content. The organizers have gathered a list of commonly asked questions from the R-help mailing list, Rseek.org and a survey of R-users. Its impact was
noticed, and \so acknowledge to "officially condone" the practice~\cite{soFlashmob09}.

The size of the R community has a network effect. As the number of its members grows, the awareness of the language increases, jobs are created, available
resources increase their size, depth and quality, new tools and libraries appear. In essence, helping individuals cope with R has benefits the entire R
community: its members learn and/or improve their expertise, the experts gain reputation for their knowledge and willingness to help, the R-users base grows and
with it, its cloud and market.

Without a single entity directing and controlling the R-language, knowlege in R has grown organically from its community. Knowledge is exchanged and curated in
many \channels (emails, blogs, books, presentations, web sites, etc). Like any other community of practice, the R-community takes advantage of available \channels
to achieve this goal.
Two \channels are at the center of this process: R-help mailing list and \so. The R-users mailing list was established \dmg{when} as way to assist those using
the language. \so is not specifically oriented towards R, but its section dedicated to the language has grown rapidly.

Without a doubt, \so has changed, for the better, the way programmers seek knowledge. \so can play the role of a expert-on-call, who is capable---and willing--
to answer questions of any level about any programming technology. The gamification features of so have also guaranteed the willingness of experts to answer
those questions, frequently within minutes of being posted. Equally important is the ability of \so users to curate the knowledge being created, making sure that
the best answers surface to the top. \so has become an effective tool to create, curate and exchange knowledge, including knowlege or R.

One would expect that the traffic in the R-users \ml would have begin to fizzle as \so popularity increses. If \so is so effective at matching those who seek
knowlege with those that have it, doesn't that obviate the need for the R-users mailing list? at least regarding questions and answers. Yet, that does not appear
to be the case. The R-help \ml continues to grow in traffic, implying that there it is still an important resource for the R-community. It appears as if R-users
and \so complement each other.

There exist obvious inherent differences between both \channnels. \mls join users by subscription, creating a tight community, and their content lacks organization (except for
its natural organization provided by the metadata of the emails---subject, threading, authors, date) and are not optimized for long term storage and retrieval.
\so, on the other hand, is a more loose community and it is opmitized for the curation and long term storage of the knowledge.

However, little is known of the actual differences of use between both \channels. 
In particular, how the questions and answers seeked in one channel compare to
the other, why users choose one channel over the other and why some users participate in both channels and what are the perceptions that its participants have
regarding each \channel.

The objective of this study is to emprically compare how knowledge, specifically knowledge manifested as questions-and-answers, is seeked, shared and curated in
both, the R-users mailing list and the R section of \so.



those providing knowledge must seek to explicitly answer questions at a particular time. Who is likely to read
a question is unknown. While \mls place postings in the mailboxes of their users, \so relies on its users to go to \so and 



The creation and curation of knowledge regarding R has a long impact that
goes well beyong simply helping new users of the language.



results in a
better, richer envinonment





- Dice Tech Salary Survey: 

 
 there was as a message in R-help mailing list to participate in a "flashmob" and seed Stack Overflow with questions.


soFlashmob09 http://conferences.oreilly.com/oscon/oscon2009/public/schedule/detail/10432

rflashmob09 https://blog.stackoverflow.com/2009/07/stack-overflow-flash-mobs/


* <2016-01-24 Sun>

To email

\dmg{This should be removed, it does not add much and it is hand-waving. Also, the text does not really reflect the subject.}

\subsubsection{Choose a channel according to the user experience}
            
    The variety of communication channels can be overwhelming to decide in which channel post.
    It is advisable to learn the characteristics of the channels before making a decision.
    For example, using Stack Overflow has benefits such as low response time~\cite{Mamykina2011} and peer recognition~\cite{Singer2013}, but user manuals should be read prior participation.
    A bad reputation in the channel might affect users in real life~\cite{Singer2013}.
    U14 pointed that one of the biggest challenges of using Stack Overflow is learning the \emph{ethos} of the channel.
    
    Communities like R, have multiple channels with overlapping functionality.
    The R-help mailing list can be used for the same purpose as Stack Overflow, but it has a different audience, which might bring some benefits.
    For instance, the R-help mailing list is less confronting, it can be used to learn rather than just get the answer, and it can be sometimes friendlier.
    
    Squire's study~\cite{Squire2015a} as well as our findings suggest that Stack Overflow might not be enough to fully support software developers.
    As it is suggested by the amount of active users on the R-help mailing list, a community might require a place to discuss topics that are in and out of the software development domain.
    The fragmentation of topics within the Stack Exchange's Q\&A channels (each channel from Stack Exchange supports a small group of topics), the complex rules of their sites, and the gamification mechanism might be a difficult issue to handle for some users~\cite{Vasilescu2013}.


          \begin{comment}
\emph{How-to}                                                                                                                                        & Ask how to do something specific.                                                                                    & 166          & 103              & 41.50\%        & 25.75\%         \\

\emph{Bug/Error\-/Exception}                                                                                                                         & Ask for a solution or reasons for a error message.                                                                   & 27           & 48               & 6.75\%         & 12.00\%         \\
\emph{Discrepancy}                                                                                                                                   & Ask about an unexpected result of a specific function, process, or package.                                          & 53           & 88               & 13.25\%        & 22.00\%         \\
\emph{Set-up}                                                                                                                                        & Ask for possible ways to set up the R environment before or after deployment.                                        & 15           & 31               & 3.75\%         & 7.75\%          \\
\emph{Decision help}                                                                                                                                 & Ask for advice in making a decision.                                                                                 & 36           & 35               & 9.00\%         & 8.75\%          \\
\emph{Conceptual\-/Guidance}                                                                                                                         & The user requests a conceptual clarification or guidance on topics related with R or statistics.                     & 48           & 49               & 12.00\%        & 12.25\%         \\
\emph{Code reviewing}                                                                                                                                & Ask for code review, explicitly or implicitly.                                                                       & 34           & 21               & 8.50\%         & 5.25\%          \\
\emph{Non-functional}                                                                                                                                & Ask for help (or suggestions) with a non-functional requirement such as performance, and memory usage.               & 14           & 11               & 3.50\%         & 2.75\%          \\
\emph{Future reference}
                                                                                                                                                                   & Ask---and normally answer itself---that might not exist on the channel, but that are interesting enough to create a thread for future reference.                                                                                                          & 5                                                                                                                    & 4            & 1.25\%           & 1.00\%                           \\
\emph{Other}                                                                                                                                         & Ask for assistance unrelated to the channel or the message contains unrelated information (e.g.,
                                                                                                                                                     announcements, ideas for improvement).                                                                 & 2                                                                                                                    & 10           & 0.50\%           & 2.50\%                           \\
&& \textbf{807} & \textbf{579}     & \textbf{100\%} & \textbf{100\%}  \\
\hline
     \multicolumn{2}{@{}l}{\textbf{Answers}}                                                                                                                                                                                                                                                                                                             \\[0.2em]
    	\emph{Redirecting}                                                                                                                                   & Provides a link to an existing solution that is not in the thread (e.g. external application, tutorial, or project). & 163          & 87               & 20.20\%        & 15.03\%         \\
    	\emph{Tutorial}                                                                                                                                      & A set of steps in order to teach people how to solve the issue.                                                      & 105          & 15               & 13.01\%        & 2.59\%          \\
    	\emph{Source code}                                                                                                                                   & Source code snippet as the solution without an extensive explanation about the answer.                               & 198          & 102              & 24.54\%        & 17.62\%         \\
    	\emph{Clue/Suggestion/Hint}                                                                                                                          & Possible ways to solve the issue without solving it.                                                                 & 43           & 105              & 5.33\%         & 18.13\%         \\
    	\emph{Alternative}                                                                                                                                   & A different approach to a solution that is related to but not exactly what is being asked for (e.g. mathematical approach, data structure modification). & 33 & 98           & 4.09\%           & 16.93\%                          \\
    	\emph{Explanation}                                                                                                                                   & Explains an approach that answers the question and lists steps on how to do it.                                      & 203          & 101              & 25.15\%        & 17.44\%         \\
    	\emph{Announcement}                                                                                                                                  & Provides a notification about some artifact (e.g., packages, libraries).                                             & 8            & 33               & 0.99\%         & 5.70\%          \\
    	\emph{Benchmark}                                                                                                                                     & Provides a benchmark of multiple solutions posted by others or compares different answers.                           & 5            & 3                & 0.62\%         & 0.52\%          \\
    	\emph{Opinion}                                                                                                                                       & Provides their own opinion or expands other answers by adding scenarios and examples.                                & 49           & 35               & 6.07\%         & 6.04\%          \\
                                                                                                                                                             & & \textbf{613} & \textbf{247}     & \textbf{0.9999 & \textbf{0.9999} \\
\hline
       \multicolumn{2}{@{}l}{\textbf{Updates}}                                                                                                                                                                                                                                                                                                           \\[0.2em]
    	\emph{Announcement}                                                                                                                                  & Announces specific events (e.g., bounties, future updates).                                                          & 27           & 3                & 4.40\%         & 1.21\%          \\
    	\emph{Background}                                                                                                                                    & Adds additional context to the question or answer                                                                    & 74           & 57               & 12.07\%        & 23.08\%         \\
    	\emph{Correction}                                                                                                                                    & Corrects format, grammar, spelling, and semantic mistakes.                                                           & 301          & 2                & 49.10\%        & 0.81\%          \\
    	\emph{Expansion}                                                                                                                                     & Expands the question or answer by providing scenarios or examples.                                                   & 116          & 83               & 18.92\%        & 33.60\%         \\
    	\emph{Explanation}                                                                                                                                   & Explains or clarifies a specific point in the question or answer, such as why the user chose a specific data structure, or the meaning of a variable.& 83                                                                                                                   & 95           & 13.54\%          & 38.46\%                          \\
    	\emph{Solution}                                                                                                                                      & The user answers their own question.                                                                                 & 12           & 7                & 1.96\%         & 2.83\%          \\
                                                                                                                                                             &                                                                                                                      & \textbf{613} & \textbf{247}     & \textbf{100} | \textbf{100}      \\
\multicolumn{2}{@{}l}{\textbf{Flags}} \\
\emph{Off-topic/opinion} & Identify questions that are unrelated to the channels' interests or which answers are based on the opinion of channel participants (not actual facts). & 22 & 19 & 27.16\% & 35.19\% \\
\emph{Not an answer} & Emphasize \textit{alternative answers} out of the scope of the question, or to identify that a solution does not answer the question. & 0                                                                     & 27          & 0.00\%       & 50.00\%           \\
\emph{Repeated question}             & Notifies user that question has been answered previously.             & 48          & 8            & 59.26\% & 14.81\% \\
\emph{Too localized}                 & Questions that are too specific and might not help any future reader. & 6           & 0            & 7.41\%  & 0.00\%  \\
\emph{Unclear}                       & Questions that are difficult to understand.                           & 5           & 0            & 6.17\%  & 0.00\%  \\
& & \textbf{81}                                                           & \textbf{54} & \textbf{100} & \textbf{100}      \\
    
            \multicolumn{2}{@{}l}{\textbf{Comments}}\\[0.2em]
            \emph{Clarification}                                                                                                                                                                                                                                                                                                         & Provides (or requests) additional information about a question or answer.                  & 98  & 28     & 17.44\% & 10.49\% \\
            \emph{Expansion}                                                                                                                                                                                                                                                                                                             & Provides additional information.                                                           & 127 & 65     & 22.60\% & 24.34\% \\
            \emph{Correction/alternative}                                                                                                                                                                                                                                                                                                & Suggests a change to a question or answer, offers an alternative solution or a correction. & 102 & 89     & 18.15\% & 33.33\% \\
            \emph{Compliment/criticism}                                                                                                                                                                                                                                                                                                  & Posts something good, offers thanks, provides an opinion or criticise someone.             & 157 & 52     & 27.94\% & 19.48\% \\
            \emph{External reference}                                                                                                                                                                                                                                                                                                    & References an external resource.                                                           & 78  & 33     & 13.88\% & 12.36\% \\
            & \textbf{562}& \textbf{267}&\textbf{100}& \textbf{100} \\
            \bottomrule
          \end{comment}
